version: "3"

services:
  nginx:
    build: ./.docker/nginx
    networks: 
      - node-network
    ports: 
      - "8080:80"
    depends_on: 
      - app 

  app:
    build: .
    networks: 
      - node-network
    volumes: 
      - .:/usr/src/app
    tty: true
    depends_on: 
       - db

  db:
    build: ./.docker/mysql
    command: --innodb-use-native-aio=0
    tty: true
    volumes: 
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/initdb:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network

networks: 
  node-network:
    driver: bridge

